version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: circleci/node:6.11.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install DEPS
          command: npm install -g bower grunt grunt-cli grunt-karma karma --save-dev

      - run:
          name: install-npm-wee
          command: ls && npm install

      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "86:6d:6a:1e:03:e6:a9:68:13:53:6e:6a:0b:dd:8c:17"

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
